### ISSUE TITLE
Find 7z.exe when not in PATH

### ISSUE THREAD

**Issue by awakecoding** [Devolutions/devolutions-labs#70]
The current scripts instruct to install the 7-Zip command-line tool, but for cases where it wasn't previously installed, it may not be immediately available in PATH (or simply not added to PATH). Improve the script to detect its install location instead of expecting it to always be in PATH and avoid this small annoyance.

**Comment by smoonlee** [comment]
Have some sample code - tested using the Windows Sandbox Windows 11 Image. 
The below code has been tested using the 7zip 24.01 Beta Applications using the executable download files.


## PowerShell Code
``` powershell
# 7zip Application Paths 
$7zipPath64x = 'C:\Program Files\7-Zip\7z.exe'
$7zipPath32x = 'C:\Program Files (x86)\7-Zip\7z.exe'

If (Test-Path $7zipPath32x) {
Write-Output "[7zip 32x] found, Creating Session Alias"
Set-Alias 7z $7zipPath32x
}

If (Test-Path $7zipPath64x) {
Write-Output "[7zip 64x] found, Creating Session Alias"
Set-Alias 7z $7zipPath64x
}
```


## Test Result - 7zipPath32x

![image](https://github.com/Devolutions/devolutions-labs/assets/22956963/efa0b135-a7bd-487b-97e2-5fe3752fbcb0)

## Test Result - 7zipPath64x

![image](https://github.com/Devolutions/devolutions-labs/assets/22956963/70eed234-d18b-4403-9c24-b366efe395f2)

## alternative - Having thrown the sample code at GitHub Copilot, It returned this:

``` powershell
# 7-Zip Application Paths
$7zipPath64x = 'C:\Program Files\7-Zip\7z.exe'
$7zipPath32x = 'C:\Program Files (x86)\7-Zip\7z.exe'

# Function to create session alias
function Create-7zAlias {
    param (
        [string]$AliasPath,
        [string]$AliasName = '7z'
    )

    if (Test-Path $AliasPath) {
        Write-Output "[$AliasName] found at $AliasPath, Creating Session Alias"
        Set-Alias -Name $AliasName -Value $AliasPath
    } else {
        Write-Output "[$AliasName] not found at $AliasPath"
    }
}

# Check and create alias for 32-bit 7-Zip
Create-7zAlias -AliasPath $7zipPath32x -AliasName '7z_32x'

# Check and create alias for 64-bit 7-Zip
Create-7zAlias -AliasPath $7zipPath64x -AliasName '7z_64x'
```

## Test Result - 7zipPath32x

![image](https://github.com/Devolutions/devolutions-labs/assets/22956963/d32763fb-d0c2-489f-887f-60a7c30c6305)

## Test Result - 7zipPath64x

![image](https://github.com/Devolutions/devolutions-labs/assets/22956963/cd192c97-5d6d-40d8-98d2-f9900b8e53a5)

**Comment by awakecoding** [comment]
Fixed by https://github.com/Devolutions/devolutions-labs/pull/71
